services:
  db:
    image: mysql:latest
    volumes:
      - ./mysql_db:/var/lib/mysql
    ports:
      - "12345:3306"
    env_file:
      - .env
    restart: on-failure
  web:
    image: nginx:alpine
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"